USER_NOT_FOUND = {err: "Usuario no encontrado", err_code: '001'}
INVALID_PROFILE_PICTURE = {err: 'Foto de perfil invalida', err_code: '002'}
CLASS_INITIALIZED = {err: 'Esta clase ya ha sido dictada hoy', err_code: '003'}
CLASS_FINISHED = {err: 'La clase ha finalizado', err_code: '004'}
EMAIL_SENT = {msg: 'Correo enviado', err_code: '005'}
USER_DELETED = {msg: 'Usuario eliminado correctamente', err_code: '006'}
CLASS_DELETED = {msg: 'Clase eliminada correctamente', err_code: '007'}
STATISTICS_ERROR = {err: "Esta clase no tiene estadisticas", err_code: '008'}
USERS_ADDED = {msg: 'Usuarios agregados correctamente', err_code: '009'}
USERS_ADDED_ERROR = {err: 'Error al agregar usuarios', err_code: '010'}
ATTENDANCE = {msg: "Llamado a lista completado correctamente", err_code: '011'}
ATTENDANCE_ERROR = {err: "Error al completar llamado a lista", err_code: '012'}
USER_PERMISSIONS = {err: "El usuario no tiene persmisos para acceder a este contenido", err_code: '013'}
TRANSACTION_ERROR = {err: 'Se ha presentado un error realizando la transacción', code: '014'}
PER_PAGE = 10