USER_NOT_FOUND = {err: "Usuario no encontrado"}
INVALID_PROFILE_PICTURE = {err: 'Foto de perfil invalida'}
CLASS_INITIALIZED = {err: 'Esta clase ya ha sido dictada hoy'}
CLASS_FINISHED = {err: 'La clase ha finalizado'}
EMAIL_SENT = {msg: 'Correo enviado'}
USER_DELETED = {msg: 'Usuario eliminado correctamente'}
CLASS_DELETED = {msg: 'Clase eliminada correctamente'}
STATISTICS_ERROR = {err: "Esta clase no tiene estadisticas"}
USERS_ADDED = {msg: 'Usuarios agregados correctamente'}
USERS_ADDED_ERROR = {err: 'Error al agregar usuarios'}
ATTENDANCE = {msg: "Llamado a lista completado correctamente"}
ATTENDANCE_ERROR = {err: "Error al completar llamado a lista"}
PER_PAGE = 10